version: "3.9"
services:
  backend:
    image: node:20-alpine
    container_name: prescripto-backend-ci
    restart: unless-stopped
    working_dir: /app
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    ports:
      - "5000:4000"
    command: sh -c "npm install && npm start"
    networks:
      - prescripto

  client:
    image: node:20-alpine
    container_name: prescripto-client-ci
    restart: unless-stopped
    working_dir: /app
    volumes:
      - ./clientside:/app
    environment:
      - VITE_BACKEND_URL=http://3.110.123.222:5000
    depends_on:
      - backend
    ports:
      - "6000:5173"
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0 --port 5173"
    networks:
      - prescripto

  admin:
    image: node:20-alpine
    container_name: prescripto-admin-ci
    restart: unless-stopped
    working_dir: /app
    volumes:
      - ./admin:/app
    environment:
      - VITE_BACKEND_URL=http://3.110.123.222:5000
    depends_on:
      - backend
    ports:
      - "6001:5174"
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0 --port 5174"
    networks:
      - prescripto

networks:
  prescripto:
    driver: bridge
